#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBangDiaCD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBangDia")]
	public partial class qlCDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void UpdateChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void DeleteChiTietPhieuThue(ChiTietPhieuThue instance);
    partial void InsertCongTy(CongTy instance);
    partial void UpdateCongTy(CongTy instance);
    partial void DeleteCongTy(CongTy instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiBangDia(LoaiBangDia instance);
    partial void UpdateLoaiBangDia(LoaiBangDia instance);
    partial void DeleteLoaiBangDia(LoaiBangDia instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhieuThue(PhieuThue instance);
    partial void UpdatePhieuThue(PhieuThue instance);
    partial void DeletePhieuThue(PhieuThue instance);
    partial void InsertThongTinBangDia(ThongTinBangDia instance);
    partial void UpdateThongTinBangDia(ThongTinBangDia instance);
    partial void DeleteThongTinBangDia(ThongTinBangDia instance);
    #endregion
		
		public qlCDDataContext() : 
				base(global::QuanLyBangDiaCD.Properties.Settings.Default.QuanLyBangDiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qlCDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlCDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlCDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlCDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietPhieuThue> ChiTietPhieuThues
		{
			get
			{
				return this.GetTable<ChiTietPhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<CongTy> CongTies
		{
			get
			{
				return this.GetTable<CongTy>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiBangDia> LoaiBangDias
		{
			get
			{
				return this.GetTable<LoaiBangDia>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhieuThue> PhieuThues
		{
			get
			{
				return this.GetTable<PhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinBangDia> ThongTinBangDias
		{
			get
			{
				return this.GetTable<ThongTinBangDia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuThue")]
	public partial class ChiTietPhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCTHD;
		
		private string _maPhieu;
		
		private System.Nullable<int> _soLuong;
		
		private EntitySet<ThongTinBangDia> _ThongTinBangDias;
		
		private EntityRef<PhieuThue> _PhieuThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTHDChanging(string value);
    partial void OnmaCTHDChanged();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    #endregion
		
		public ChiTietPhieuThue()
		{
			this._ThongTinBangDias = new EntitySet<ThongTinBangDia>(new Action<ThongTinBangDia>(this.attach_ThongTinBangDias), new Action<ThongTinBangDia>(this.detach_ThongTinBangDias));
			this._PhieuThue = default(EntityRef<PhieuThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCTHD
		{
			get
			{
				return this._maCTHD;
			}
			set
			{
				if ((this._maCTHD != value))
				{
					this.OnmaCTHDChanging(value);
					this.SendPropertyChanging();
					this._maCTHD = value;
					this.SendPropertyChanged("maCTHD");
					this.OnmaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="Char(5)")]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					if (this._PhieuThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietPhieuThue_ThongTinBangDia", Storage="_ThongTinBangDias", ThisKey="maCTHD", OtherKey="maCTHD")]
		public EntitySet<ThongTinBangDia> ThongTinBangDias
		{
			get
			{
				return this._ThongTinBangDias;
			}
			set
			{
				this._ThongTinBangDias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuThue_ChiTietPhieuThue", Storage="_PhieuThue", ThisKey="maPhieu", OtherKey="maPhieu", IsForeignKey=true, DeleteRule="CASCADE")]
		public PhieuThue PhieuThue
		{
			get
			{
				return this._PhieuThue.Entity;
			}
			set
			{
				PhieuThue previousValue = this._PhieuThue.Entity;
				if (((previousValue != value) 
							|| (this._PhieuThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuThue.Entity = null;
						previousValue.ChiTietPhieuThues.Remove(this);
					}
					this._PhieuThue.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuThues.Add(this);
						this._maPhieu = value.maPhieu;
					}
					else
					{
						this._maPhieu = default(string);
					}
					this.SendPropertyChanged("PhieuThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietPhieuThue = this;
		}
		
		private void detach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietPhieuThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTy")]
	public partial class CongTy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCongTy;
		
		private string _tenCongTy;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private EntitySet<ThongTinBangDia> _ThongTinBangDias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCongTyChanging(string value);
    partial void OnmaCongTyChanged();
    partial void OntenCongTyChanging(string value);
    partial void OntenCongTyChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    #endregion
		
		public CongTy()
		{
			this._ThongTinBangDias = new EntitySet<ThongTinBangDia>(new Action<ThongTinBangDia>(this.attach_ThongTinBangDias), new Action<ThongTinBangDia>(this.detach_ThongTinBangDias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTy", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCongTy
		{
			get
			{
				return this._maCongTy;
			}
			set
			{
				if ((this._maCongTy != value))
				{
					this.OnmaCongTyChanging(value);
					this.SendPropertyChanging();
					this._maCongTy = value;
					this.SendPropertyChanged("maCongTy");
					this.OnmaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCongTy", DbType="NVarChar(60)")]
		public string tenCongTy
		{
			get
			{
				return this._tenCongTy;
			}
			set
			{
				if ((this._tenCongTy != value))
				{
					this.OntenCongTyChanging(value);
					this.SendPropertyChanging();
					this._tenCongTy = value;
					this.SendPropertyChanged("tenCongTy");
					this.OntenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="Char(12)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_ThongTinBangDia", Storage="_ThongTinBangDias", ThisKey="maCongTy", OtherKey="maCongTy")]
		public EntitySet<ThongTinBangDia> ThongTinBangDias
		{
			get
			{
				return this._ThongTinBangDias;
			}
			set
			{
				this._ThongTinBangDias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = this;
		}
		
		private void detach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.CongTy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _hoTenKH;
		
		private string _gioiTinh;
		
		private string _SDT;
		
		private string _diaChi;
		
		private EntitySet<PhieuThue> _PhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnhoTenKHChanging(string value);
    partial void OnhoTenKHChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._PhieuThues = new EntitySet<PhieuThue>(new Action<PhieuThue>(this.attach_PhieuThues), new Action<PhieuThue>(this.detach_PhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenKH", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string hoTenKH
		{
			get
			{
				return this._hoTenKH;
			}
			set
			{
				if ((this._hoTenKH != value))
				{
					this.OnhoTenKHChanging(value);
					this.SendPropertyChanging();
					this._hoTenKH = value;
					this.SendPropertyChanged("hoTenKH");
					this.OnhoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuThue", Storage="_PhieuThues", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<PhieuThue> PhieuThues
		{
			get
			{
				return this._PhieuThues;
			}
			set
			{
				this._PhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiBangDia")]
	public partial class LoaiBangDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<ThongTinBangDia> _ThongTinBangDias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public LoaiBangDia()
		{
			this._ThongTinBangDias = new EntitySet<ThongTinBangDia>(new Action<ThongTinBangDia>(this.attach_ThongTinBangDias), new Action<ThongTinBangDia>(this.detach_ThongTinBangDias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(50)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBangDia_ThongTinBangDia", Storage="_ThongTinBangDias", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<ThongTinBangDia> ThongTinBangDias
		{
			get
			{
				return this._ThongTinBangDias;
			}
			set
			{
				this._ThongTinBangDias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBangDia = this;
		}
		
		private void detach_ThongTinBangDias(ThongTinBangDia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiBangDia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _hoTenNV;
		
		private string _SDT;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private System.Nullable<decimal> _luong;
		
		private System.Nullable<int> _caLamViec;
		
		private EntitySet<PhieuThue> _PhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnhoTenNVChanging(string value);
    partial void OnhoTenNVChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnluongChanging(System.Nullable<decimal> value);
    partial void OnluongChanged();
    partial void OncaLamViecChanging(System.Nullable<int> value);
    partial void OncaLamViecChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhieuThues = new EntitySet<PhieuThue>(new Action<PhieuThue>(this.attach_PhieuThues), new Action<PhieuThue>(this.detach_PhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenNV", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string hoTenNV
		{
			get
			{
				return this._hoTenNV;
			}
			set
			{
				if ((this._hoTenNV != value))
				{
					this.OnhoTenNVChanging(value);
					this.SendPropertyChanging();
					this._hoTenNV = value;
					this.SendPropertyChanged("hoTenNV");
					this.OnhoTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="Money")]
		public System.Nullable<decimal> luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this.OnluongChanging(value);
					this.SendPropertyChanging();
					this._luong = value;
					this.SendPropertyChanged("luong");
					this.OnluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caLamViec", DbType="Int")]
		public System.Nullable<int> caLamViec
		{
			get
			{
				return this._caLamViec;
			}
			set
			{
				if ((this._caLamViec != value))
				{
					this.OncaLamViecChanging(value);
					this.SendPropertyChanging();
					this._caLamViec = value;
					this.SendPropertyChanged("caLamViec");
					this.OncaLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuThue", Storage="_PhieuThues", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<PhieuThue> PhieuThues
		{
			get
			{
				return this._PhieuThues;
			}
			set
			{
				this._PhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuThues(PhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuThue")]
	public partial class PhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhieu;
		
		private string _maKH;
		
		private string _maNV;
		
		private System.Nullable<System.DateTime> _ngayMuon;
		
		private System.Nullable<System.DateTime> _ngayTra;
		
		private EntitySet<ChiTietPhieuThue> _ChiTietPhieuThues;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuChanging(string value);
    partial void OnmaPhieuChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnngayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnngayMuonChanged();
    partial void OnngayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnngayTraChanged();
    #endregion
		
		public PhieuThue()
		{
			this._ChiTietPhieuThues = new EntitySet<ChiTietPhieuThue>(new Action<ChiTietPhieuThue>(this.attach_ChiTietPhieuThues), new Action<ChiTietPhieuThue>(this.detach_ChiTietPhieuThues));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieu", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieu
		{
			get
			{
				return this._maPhieu;
			}
			set
			{
				if ((this._maPhieu != value))
				{
					this.OnmaPhieuChanging(value);
					this.SendPropertyChanging();
					this._maPhieu = value;
					this.SendPropertyChanged("maPhieu");
					this.OnmaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Char(5)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="Char(5)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayMuon", DbType="Date")]
		public System.Nullable<System.DateTime> ngayMuon
		{
			get
			{
				return this._ngayMuon;
			}
			set
			{
				if ((this._ngayMuon != value))
				{
					this.OnngayMuonChanging(value);
					this.SendPropertyChanging();
					this._ngayMuon = value;
					this.SendPropertyChanged("ngayMuon");
					this.OnngayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTra", DbType="Date")]
		public System.Nullable<System.DateTime> ngayTra
		{
			get
			{
				return this._ngayTra;
			}
			set
			{
				if ((this._ngayTra != value))
				{
					this.OnngayTraChanging(value);
					this.SendPropertyChanging();
					this._ngayTra = value;
					this.SendPropertyChanged("ngayTra");
					this.OnngayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuThue_ChiTietPhieuThue", Storage="_ChiTietPhieuThues", ThisKey="maPhieu", OtherKey="maPhieu")]
		public EntitySet<ChiTietPhieuThue> ChiTietPhieuThues
		{
			get
			{
				return this._ChiTietPhieuThues;
			}
			set
			{
				this._ChiTietPhieuThues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuThue", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true, DeleteRule="CASCADE")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuThues.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuThues.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuThue", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteRule="CASCADE")]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuThues.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuThues.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.PhieuThue = this;
		}
		
		private void detach_ChiTietPhieuThues(ChiTietPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.PhieuThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinBangDia")]
	public partial class ThongTinBangDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maBangDia;
		
		private string _maLoai;
		
		private string _maCongTy;
		
		private string _maCTHD;
		
		private string _tenBangDia;
		
		private string _theLoai;
		
		private string _tinhTrang;
		
		private System.Nullable<System.DateTime> _ngaySX;
		
		private string _ghiChu;
		
		private System.Nullable<decimal> _gia;
		
		private EntityRef<CongTy> _CongTy;
		
		private EntityRef<ChiTietPhieuThue> _ChiTietPhieuThue;
		
		private EntityRef<LoaiBangDia> _LoaiBangDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBangDiaChanging(string value);
    partial void OnmaBangDiaChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OnmaCongTyChanging(string value);
    partial void OnmaCongTyChanged();
    partial void OnmaCTHDChanging(string value);
    partial void OnmaCTHDChanged();
    partial void OntenBangDiaChanging(string value);
    partial void OntenBangDiaChanged();
    partial void OntheLoaiChanging(string value);
    partial void OntheLoaiChanged();
    partial void OntinhTrangChanging(string value);
    partial void OntinhTrangChanged();
    partial void OnngaySXChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySXChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    #endregion
		
		public ThongTinBangDia()
		{
			this._CongTy = default(EntityRef<CongTy>);
			this._ChiTietPhieuThue = default(EntityRef<ChiTietPhieuThue>);
			this._LoaiBangDia = default(EntityRef<LoaiBangDia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBangDia", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maBangDia
		{
			get
			{
				return this._maBangDia;
			}
			set
			{
				if ((this._maBangDia != value))
				{
					this.OnmaBangDiaChanging(value);
					this.SendPropertyChanging();
					this._maBangDia = value;
					this.SendPropertyChanged("maBangDia");
					this.OnmaBangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Char(5)")]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._LoaiBangDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTy", DbType="Char(5)")]
		public string maCongTy
		{
			get
			{
				return this._maCongTy;
			}
			set
			{
				if ((this._maCongTy != value))
				{
					if (this._CongTy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCongTyChanging(value);
					this.SendPropertyChanging();
					this._maCongTy = value;
					this.SendPropertyChanged("maCongTy");
					this.OnmaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHD", DbType="Char(5)")]
		public string maCTHD
		{
			get
			{
				return this._maCTHD;
			}
			set
			{
				if ((this._maCTHD != value))
				{
					if (this._ChiTietPhieuThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCTHDChanging(value);
					this.SendPropertyChanging();
					this._maCTHD = value;
					this.SendPropertyChanged("maCTHD");
					this.OnmaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenBangDia", DbType="NVarChar(60)")]
		public string tenBangDia
		{
			get
			{
				return this._tenBangDia;
			}
			set
			{
				if ((this._tenBangDia != value))
				{
					this.OntenBangDiaChanging(value);
					this.SendPropertyChanging();
					this._tenBangDia = value;
					this.SendPropertyChanged("tenBangDia");
					this.OntenBangDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theLoai", DbType="NVarChar(60)")]
		public string theLoai
		{
			get
			{
				return this._theLoai;
			}
			set
			{
				if ((this._theLoai != value))
				{
					this.OntheLoaiChanging(value);
					this.SendPropertyChanging();
					this._theLoai = value;
					this.SendPropertyChanged("theLoai");
					this.OntheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="NVarChar(10)")]
		public string tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySX", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySX
		{
			get
			{
				return this._ngaySX;
			}
			set
			{
				if ((this._ngaySX != value))
				{
					this.OnngaySXChanging(value);
					this.SendPropertyChanging();
					this._ngaySX = value;
					this.SendPropertyChanged("ngaySX");
					this.OnngaySXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(100)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTy_ThongTinBangDia", Storage="_CongTy", ThisKey="maCongTy", OtherKey="maCongTy", IsForeignKey=true, DeleteRule="CASCADE")]
		public CongTy CongTy
		{
			get
			{
				return this._CongTy.Entity;
			}
			set
			{
				CongTy previousValue = this._CongTy.Entity;
				if (((previousValue != value) 
							|| (this._CongTy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTy.Entity = null;
						previousValue.ThongTinBangDias.Remove(this);
					}
					this._CongTy.Entity = value;
					if ((value != null))
					{
						value.ThongTinBangDias.Add(this);
						this._maCongTy = value.maCongTy;
					}
					else
					{
						this._maCongTy = default(string);
					}
					this.SendPropertyChanged("CongTy");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietPhieuThue_ThongTinBangDia", Storage="_ChiTietPhieuThue", ThisKey="maCTHD", OtherKey="maCTHD", IsForeignKey=true, DeleteRule="CASCADE")]
		public ChiTietPhieuThue ChiTietPhieuThue
		{
			get
			{
				return this._ChiTietPhieuThue.Entity;
			}
			set
			{
				ChiTietPhieuThue previousValue = this._ChiTietPhieuThue.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietPhieuThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietPhieuThue.Entity = null;
						previousValue.ThongTinBangDias.Remove(this);
					}
					this._ChiTietPhieuThue.Entity = value;
					if ((value != null))
					{
						value.ThongTinBangDias.Add(this);
						this._maCTHD = value.maCTHD;
					}
					else
					{
						this._maCTHD = default(string);
					}
					this.SendPropertyChanged("ChiTietPhieuThue");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiBangDia_ThongTinBangDia", Storage="_LoaiBangDia", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true, DeleteRule="CASCADE")]
		public LoaiBangDia LoaiBangDia
		{
			get
			{
				return this._LoaiBangDia.Entity;
			}
			set
			{
				LoaiBangDia previousValue = this._LoaiBangDia.Entity;
				if (((previousValue != value) 
							|| (this._LoaiBangDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiBangDia.Entity = null;
						previousValue.ThongTinBangDias.Remove(this);
					}
					this._LoaiBangDia.Entity = value;
					if ((value != null))
					{
						value.ThongTinBangDias.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("LoaiBangDia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
